name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Configure Maven settings for GitHub Packages
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Cache Maven local repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: Build with Maven
      run: mvn -B clean package

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: alunoonline-war
        path: target/*.war

           # ——— new deploy steps below ———

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ecs-key.pem
        chmod 600 ~/.ssh/ecs-key.pem

   - name: Stop Tomcat
      run: |
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ecs-key.pem \
            ec2-user@15.228.77.0 \
            '/opt/tomcat8/bin/catalina.sh stop'

    - name: Clean out old WAR and exploded app
      run: |
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ecs-key.pem \
            ec2-user@15.228.77.0 \
            'sudo rm -f /opt/tomcat8/webapps/*.war \
                  && sudo rm -rf /opt/tomcat8/webapps/alunoonline'

    - name: Upload new WAR
      run: |
        scp -o StrictHostKeyChecking=no \
            -i ~/.ssh/ecs-key.pem \
            target/*.war \
            ec2-user@15.228.77.0:/opt/tomcat8/webapps/alunoonline.war

    - name: Start Tomcat
      run: |
        ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ecs-key.pem \
            ec2-user@15.228.77.0 \
            '/opt/tomcat8/bin/catalina.sh start'

